apiVersion: apps/v1
kind: Deployment
metadata:
  name: flume
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: flume
  template:
    metadata:
      labels:
        app: flume
    spec:
      nodeSelector:
        kubernetes.io/arch : armv7
      containers:
        - name: flume
          image: dodok8/raspbian-flume:v0.0.6
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]