apiVersion: apps/v1
kind: Deployment
metadata:
  name: flume
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: flume
  template:
    metadata:
      labels:
        app: flume
    nodeSelector:
      kubernetes.io/arch : armv7
    spec:
      containers:
        - name: flume
          image: dodok8/raspbian-flume:latest