apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      nodeSelector:
        kubernetes.io/arch : amd64
      containers:
        - name: zookeeper
          image: dodok8/ubuntu-kafka:v0.0.4
        - name: broker0
          image: dodok8/ubuntu-kafka:v0.0.4
        - name: broker1
          image: dodok8/ubuntu-kafka:v0.0.4
        - name: broker2
          image: dodok8/ubuntu-kafka:v0.0.4
        - name: consumer
          image: dodok8/ubuntu-kafka:v0.0.3