apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: smartx
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kafka
  nodeSelector:
    kubernetes.io/arch : amd64
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: zookeeper
          image: dodok8/ubuntu-kafka:latest
        - name: broker0
          image: dodok8/ubuntu-kafka:latest
        - name: broker1
          image: dodok8/ubuntu-kafka:latest
        - name: broker2
          image: dodok8/ubuntu-kafka:latest
        - name: consumer
          image: dodok8/ubuntu-kafka:latest